// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztnppmdgdobqixqgbskn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bnBwbWRnZG9icWl4cWdic2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzY2MzQsImV4cCI6MjA2MDcxMjYzNH0.6es656foboCW76KcosxZGE_WRIyYRnV3iWWHW9RPS5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);